### ISSUE TITLE
[Bug Report] Black screen error when installing retroarch.

### ISSUE THREAD

**Issue by wuniversales** [Universal-Team/Universal-Updater#64]
**Describe the bug**
The program causes a black screen when trying to install Retroarch.

**To Reproduce**

- Open Universal updater.
- Find Retroarch.
- Download the 3dsx file.
- Try to install it.

**Expected behavior**
It shouldn't give a black screen error.

**Console/Version (please complete the following information):**

  Console :

  - [x] 3DS
  - [ ] 3DS XL
  - [ ] 2DS
  - [ ] New 3DS
  - [ ] New 3DS XL
  - [ ] New 2DS XL

  Luma & System version: Latest

Luma 3DS version: v10.2.1
System version & Region: Sys 11.14.0-46E

**Universal-Updater (please complete the following information):**
  - [x] Release : v3.1.1
  - [ ] Nightly

  How do you launch it:

  - [ ] cia
  - [x] 3dsx

**Additional context**

https://transfer.sh/30BOo/crash_dump_00000000.dmp

**Comment by Epicpkmn11** [comment]
You need to use the 3DSX version of Universal-Updater for RetroArch, I think the crashing should already be fixed in the latest nightly, but we're not sure of a way to fix it failing when running from CIA at the moment

**Comment by SuperSaiyajinStackZ** [comment]
For the Nightly you'll have to build it yourself tho, cause devkitPro's docker image is still not updated iirc and crashes with empty newline descriptions, then.

**Comment by wuniversales** [comment]
> You need to use the 3DSX version of Universal-Updater for RetroArch, I think the crashing should already be fixed in the latest nightly, but we're not sure of a way to fix it failing when running from CIA at the moment

In my case I run Universal Updater from 3dsx 

> For the Nightly you'll have to build it yourself tho, cause devkitPro's docker image is still not updated iirc and crashes with empty newline descriptions, then.

No idea

**Comment by SuperSaiyajinStackZ** [comment]
Also, when does it give a "blackscreen" error? When downloading? When extracting? If on extracting, then hmm, it works fine for me on 3dsx..

**Comment by wuniversales** [comment]
> Also, when does it give a "blackscreen" error? When downloading? When extracting? If on extracting, then hmm, it works fine for me on 3dsx..

When extracting, it discharges successfully.
I have sent the dump file, in case it helps.

**Comment by Epicpkmn11** [comment]
> In my case I run Universal Updater from 3dsx

Oh weird, I missed that, try with this build:
[Universal-Updater.zip](https://github.com/Universal-Team/Universal-Updater/files/5876650/Universal-Updater.zip)

**Comment by wuniversales** [comment]
Now it works fine, this appears.
https://i.imgur.com/Jpn2cMN.png
But come on, it seems that it is normal operation, correct operation.

**Comment by wuniversales** [comment]
I just saw that it seems to download wrong, The author is not shown in the homebrew launcher.
Watch this.
![image](https://user-images.githubusercontent.com/48658161/105919972-d4d28900-6036-11eb-9b38-ab8cf2291622.png)

**Comment by Epicpkmn11** [comment]
Oh, I guess it needs to have the SMDH too, I've been skipping those in Universal-DB since afaik most apps don't need them in the latest version of the homebrew launcher

I'll fix that on Universal-DB's side

**Comment by Epicpkmn11** [comment]
The proper 3DSX placement option is added as of 623436598e230e0200fda8609e83b65a042ad4e3
